import { App, Modal, ButtonComponent } from "obsidian";
import { ZettelId } from "../../core/ZettelID";
import { ReorderModal } from "../reorder/ReorderModal";
export class IDInspectorModal extends Modal {
  constructor(app:App, private boxManager:any, private zettelManager:any, private refactor:any){ super(app); }
  onOpen(){ const { contentEl } = this; contentEl.empty(); const file = this.app.workspace.getActiveFile(); if(!file){ contentEl.createEl('div',{text:'Open a Zettel file to inspect.'}); return; } const idStr = file.basename.replace(/\.md$/i,''); let parsed:ZettelId; try{ parsed = new ZettelId(idStr); } catch(e){ contentEl.createEl('div',{text:`Invalid Zettel ID: ${idStr}`}); return; } contentEl.createEl('h2',{text:`ID: ${parsed.toString()}`}); const segWrap = contentEl.createEl('div'); segWrap.createEl('h3',{text:'Segments'}); const ul = segWrap.createEl('ul'); for(const s of parsed.getSegments()) ul.createEl('li',{text:`${s.type}: ${s.value}`}); const actions = contentEl.createDiv({ cls: 'zk-inspector-actions' }); const reorderBtn = new ButtonComponent(actions); reorderBtn.setButtonText('Reorder Slipbox (open modal)').onClick(async()=>{ const box = this.boxManager.getBoxes()[0]; const forest = await this.zettelManager.getForest(box); const modal = new ReorderModal(this.app, forest, box, async(res)=>{ const conflicts = this.refactor.findConflicts(res.filePathRenameMap); if(conflicts.length){ const { ConflictConfirmationModal } = await import('../conflicts/ConflictConfirmationModal'); const items = conflicts.map((p:string)=>({ oldPath:'(unknown)', newPath:p, reason:'collision' })); await new Promise<void>((resolve)=>{ new ConflictConfirmationModal(this.app, items, async(ok)=>{ if(!ok){ resolve(); return; } await this.refactor.applyRenameMap(res.filePathRenameMap, 'Reorder apply'); resolve(); }).open(); }); } else { await this.refactor.applyRenameMap(res.filePathRenameMap, 'Reorder apply'); } }); modal.open(); }); const close = new ButtonComponent(actions); close.setButtonText('Close').onClick(()=>this.close()); }
  onClose(){ this.contentEl.empty(); }
}
export default IDInspectorModal
